version: 2.1

jobs:
  build:
    docker:
      - image: circleci/android:api-30

    working_directory: ~/ProductCatalog

    steps:
      - checkout

      # Download and install dependencies
      - run:
          name: Install Dependencies
          command: |
            yes | sdkmanager --licenses
            ./gradlew dependencies

      # Build the project
      - run:
          name: Build Project
          command: ./gradlew assembleDebug

      # Run unit tests
      - run:
          name: Run Unit Tests
          command: ./gradlew test

workflows:
  version: 2
  build:
    jobs:
      - build
